### ISSUE TITLE
References to "siblings" files not resolved

### ISSUE THREAD

**Issue by mickaelistria** [theia-ide/typescript-language-server#110]
See https://github.com/eclipse/wildwebdeveloper/issues/195 for initial report to Wild Web Developer

Imagine a project with 2 files side-by-side: function.js contains `funtion f() { console.log("hey"); }` and consumer.js contains just `function proxy() { f(); }`. In a browser, invoking `proxy()` (as a `onclick` of a button or whatever) would invoke `f();` and show message in log.
However, in Wild Web Developer, with TypeScript Language Server, `f()` is not resolved as a function while hovering, completion and so on. The link between both files is basically inexistant.
It could be an issue in tsserver that fails at assuming "sibling" files can see each other.

**Comment by rchl** [comment]
This is not a setup that the server can support. Server has no way of knowing that those two functions will be accessible in the same scope due to being included from the same html file.

The server can understand the setup that is using CommonJS or ES imports which is pretty much a norm these days. Even for developing browser pages (through transpilers and bundlers).
