### ISSUE TITLE
How to use a specific tsconfig file?

### ISSUE THREAD

**Issue by kud** [theia-ide/typescript-language-server#117]

**Comment by rchl** [comment]
Server relies on `typescript` package (or the `tserver` part of it) for looking up `tsconfig.json` file. I don't know the exact logic but I believe it will look up `tsconfig.json` up the tree from the currently opened file to the root of the project.

**Comment by daaanny90** [comment]
Sorry for opening a really old issue, but I have the very same question. I have multiple tsconfig in my project and, for some reasons, I have to use a file that is not `tsconfig.json` but `tsconfig.vitest.json`, because this is what we use in the pipeline and I just want to use the very same config to get the correct type checking while coding.

Can I define which tsconfig should be used?

**Comment by predragnikolic** [comment]
The tsserver doesn't support it.
See
https://github.com/microsoft/TypeScript/issues/33094
https://github.com/microsoft/vscode/issues/107750#issuecomment-707395518
