### ISSUE TITLE
support webpack module resolution, especially alias

### ISSUE THREAD

**Issue by cruzdanilo** [theia-ide/typescript-language-server#140]
support webpack module resolution, especially alias, when finding references or getting the definition.

**Comment by saitonakamura** [comment]
You can invert it: use [tsconfig.paths field](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) (which will solve typescript resolution) along with [tsconfig-paths-webpack-plugin](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin) (which will provide alias for webpack based on `paths`)

**Comment by weilbith** [comment]
Could someone post an example configuration to make this working? That issue is really annoying during daily work.

**Comment by weeman1337** [comment]
@weilbith here is a working config (for JavaScript, TypeScript works similar I think having a `tsconfig.json`):

`foo` modules under `src/foo`

```
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "foo/*": [
                "src/foo/*"
            ]
        }
    }
}
```

**Comment by rchl** [comment]
As said above, the solution is defined `paths` in `tsconfig.json`.

**Comment by weeman1337** [comment]
Would it make sense documenting it? Or at least extending https://github.com/theia-ide/typescript-language-server/blob/master/example/tsconfig.json ?

**Comment by rchl** [comment]
I don't think we want to document it since all typescript options are already documented by typescript (https://www.typescriptlang.org/tsconfig) and repeating that would be redundant and problematic from the maintenance point of view.

Maybe there should be some generic note in the readme that all typescript options apply to this server and can be configured through `tsconfig.json`.
