### ISSUE TITLE
Replace TSLint

### ISSUE THREAD

**Issue by DonnieWest** [theia-ide/typescript-language-server#159]
TSLint is currently [deprecated](https://github.com/palantir/tslint/issues/4534) so we should find a replacement

* Prettier
  * Gold Standard across JS and TS projects
  * We should probably implement this in one project-wide commit so we get all the pain over with at once
* ESLint
  * Currently maintained and promoted alternative to TSLint
  * Perhaps we should use something out-of-the-box like StandardJS

**Comment by DonnieWest** [comment]
Updated the issue. I'm pretty set on moving us over to Prettier/ESLint, I just need to either decide on an ESLint config or use StandardJS

**Comment by rchl** [comment]
I'm for using ESlint.

I'm not sure Prettier is a good idea. It is very opinionated which means that there is very little we can do to configure it.

As for using the StandardJS config, I'm not sure since it's not using semicolons which means it's not really in line with existing style. We could of course override rules as we please though...

So I'm for either using plain ESlint with custom rules that we would customize to fit the current code as much as possible (so that there is the least amount of changes to existing code) or use the ESlint + StandardJS and override some rules.

I typically just create custom rules for eslint in my projects (or use the company config in work-related projects). That gives the most control.

BTW. Since this is a TS project, we'd need to use `ts-standard` (https://standardjs.com/index.html#typescript) instead.

**Comment by DonnieWest** [comment]
All good points and noted on the `ts-standard`

The biggest benefit of both tools is that they _aren't_ configurable. If someone else has made those decisions, we can avoid discussion around what our lints/styles should be in the future. Additionally, these get automatically updated on our behalf so we don't need to worry about the latest-and-greatest community lints to add :)

The one major concern about that (that you brought up) is that we're not in line with current styles. That's a bummer since `git blame` won't give us the correct results. If we reformat the project correctly though, that's one giant commit and we should never have to worry about it again. Prettier and StandardJS have really low style churn because they resist change so much.

The further away from our one-big-reformat-everything commit we are, the larger the benefits we reap and the less irritating it is to stay in line with the current project

**Comment by rchl** [comment]
I've tried switching to `ts-standard` now and here are my thoughts:

Running `--fix` on the code will mainly result in those changes:
 - change indentation from 4 to 2 spaces
 - remove semicolons at the end of statements
 - add a space between function name and function parameters

I'd be fine with those changes although I'm equally fine with the current style as long as there are IDE integration and a commit hook that checks the style. I wouldn't see such changes as bringing much to the style of the code or improving it in any way.

Now here is where I see the problem. `ts-standard`(as well as `standard`) uses its own binary for linting which means that existing IDE integrations that handle linting through eslint don't work with it. For example, it's common to use `vscode-eslint` in VSCode (which I'm also using within SublimeText) and that one doesn't work with this setup as it expects an eslint configuration file in the workspace.

With that in mind, I'm really against using those "standard" solutions and would instead go for a custom eslint configuration file. I do that for various projects and I can't see any problems with that. The only potential downside is that new rules won't be added unless someone actively watches eslint project and adds them manually. But really it's not that big of a deal to not keep up with new rules.

Another benefit of custom rules is that we can adjust the rules so that they match existing code as much as possible and introduce minimal changes to it. It's not really the issue that the current code is using poor style, it's mainly about keeping the style consistent.

**Comment by whitebyte** [comment]
@rchl fully agree on this one

Also keep in mind that standard.js is not a "real" standard, it's a self-proclaimed "standard" that happened to grab a fancy package name and in fact is no more than glorifed .eslintrc. Given their past controversy (https://wptavern.com/standardjs-ends-controversial-funding-experiment) I'd suggest reconsider.

**Comment by tko** [comment]
> The one major concern about that (that you brought up) is that we're not in line with current styles. That's a bummer since `git blame` won't give us the correct results. If we reformat the project correctly though, that's one giant commit and we should never have to worry about it again.

FWIW it sounds like `blame.ignoreRevsFile` config option can help with that, https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame though I've not tried it myself.
