### ISSUE TITLE
Get weird errors for first oppened file with typescript in vim

### ISSUE THREAD

**Issue by timsofteng** [theia-ide/typescript-language-server#187]
Hello. When I first open file in vim typescript everytime highlight many wrong errors. It happens with any file but just with first.  Then it works correctly. Take a look on two screensots. It's exactly the same file without any changes. The only one difference is that file was opened as first file on first screenshot.
Whad do i do wrong?

![image](https://user-images.githubusercontent.com/51912173/108200854-b3415a80-7127-11eb-85ab-3fb36d403f50.png)
![image](https://user-images.githubusercontent.com/51912173/108201064-00bdc780-7128-11eb-8d20-6ff93ccc66d8.png)

**Comment by mohkale** [comment]
I think I've got a similair issue except I get errors with every file. If I kill my server and restart it then I don't get errors in the current file/buffer but I do get them in every other file or buffer.

**Comment by emiel** [comment]
Same issue here:

- Vim 8.2
- vim-lsp
- typescript-language-server - 0.5.1
- typescript - 4.1.5

**Comment by mohkale** [comment]
So I did a little debugging to try and track down what's causing this for me, this might help others in this issue as well.

Here's my server [log](https://github.com/theia-ide/typescript-language-server/files/6006427/tslog.log) with logging set to 4 (super-verbose). NOTE: It's for eglot so it looks a little lispy but you can think of it like a weird JSON file.

In my case the languageId field in my clients initial call to `textDocument/didOpen` was set to typescript instead of tsx. I believe in VSCode you can see this value in the footer bar but for editors like vim or emacs where it isn't readily visible this is a really easy issue to not notice. I feel like the server should at least include some linting error or something. For eg. if the file ends with tsx but the server is told its ts it should warn us there might be a configuration error.

Regardless I fixed it by updating my client to use typescriptreact instead of typescript. You can see a list of possible langaugeIds https://github.com/theia-ide/typescript-language-server/blob/3a8ea0f04bde047e2f60b9f68ef7816e3a41aa10/server/src/lsp-server.ts#L269-L277
I advise you to look into your server logs, make sure languageId is set correctly or open an issue with your client implementation.

**Comment by emiel** [comment]
Thanks @mohkale for digging into this. Based on your tip to check the `lanuageId` I found out mine was explicitly set to "typescript". I'm using vim-lsp which defaults to the detected filetype but for some reason I had it set explicitly to "typescript". After removing the override it picked up `typescriptreact` correctly and all is well again. So configuration error on my part. Sorry for the noise. ;)

**Comment by wmww** [comment]
I'm also seeing JSX-related errors in the first file opened with Kate. If the first file is a non-JSX typescript file, there are no errors. Switching to a different file and restarting typescript-language-server moves the errors from the original file to the current one (unless the current file isn't a JSX file, in which case the errors go away).

**Comment by rchl** [comment]
It looks like the issue is with the client (editor) not specifying the `languageId` correctly on first opening of the file.

Doesn't look like the server is at fault here.
