### ISSUE TITLE
Styled components support

### ISSUE THREAD

**Issue by timsofteng** [theia-ide/typescript-language-server#196]
Hello. Is it possible to add supporting for styled component? As completion suggestions and so on.
Now it's completele unsuppoted when i put styled component to .tsx .

**Comment by rchl** [comment]
Can you provide an example project that uses those?

But should say from the bat that it wouldn't really be responsibility of this project to support that. Would need to be supported either through `typescript` directly or through a typescript plugin.

**Comment by apexskier** [comment]
Personally I don't think this should be the responsibility of this project, since it would significantly change the complexity of the project. This project would need to implement it's own document parsing instead of acting as a transformation layer between the language server protocol and tsserver's typescript server protocol.

Instead, I'd suggest trying to use typescript's language service plugin feature - https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin. There's actually already one for styled-component from Microsoft - https://github.com/Microsoft/typescript-styled-plugin.

Although I haven't personally tested, it should be possible to do this using initialization options.
https://github.com/theia-ide/typescript-language-server/blob/89d22580fc64fbebd12ebd4b88bdef38f76ddf1c/server/src/ts-protocol.ts#L25

**Comment by timsofteng** [comment]
> Personally I don't think this should be the responsibility of this project, since it would significantly change the complexity of the project. This project would need to implement it's own document parsing instead of acting as a transformation layer between the language server protocol and tsserver's typescript server protocol.
> 
> Instead, I'd suggest trying to use typescript's language service plugin feature - https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin. There's actually already one for styled-component from Microsoft - https://github.com/Microsoft/typescript-styled-plugin.
> 
> Although I haven't personally tested, it should be possible to do this using initialization options.
> https://github.com/theia-ide/typescript-language-server/blob/89d22580fc64fbebd12ebd4b88bdef38f76ddf1c/server/src/ts-protocol.ts#L25

Thanks!
It works.
Closed
