### ISSUE TITLE
Does this LSP server load `.editorconfig`?

### ISSUE THREAD

**Issue by Invertisment** [theia-ide/typescript-language-server#202]
I have an issue with `Spacemacs` when I use its `ts-ls` option. If I found out correctly it uses this package.

The issue is that I have an `.editorconfig` in a monorepo project that describes formatting of 2 spaces but when the editor uses `ts-ls` (this LSP server) it formats it with 4 spaces. So `.editorconfig` is not picked up.

This is my original issue with more details:
https://github.com/syl20bnr/spacemacs/issues/14633

**Comment by lebensterben** [comment]
Duplicated https://github.com/theia-ide/typescript-language-server/issues/10

**Comment by rchl** [comment]
I'm not convinced that the server should search and read that file (even if it does that for `tsfmt.json` right now). It's the LSP client that is supposed to pass the formatting options with the `textDocument/formatting` request. So ideally the editor will decide on the spaces/indent size (reading it from `.editorconfig` or elsewhere and pass that when making the request.

Otherwise the server would have to support a myriad ways of specifying that information and it's very much against the goal of LSP.

@Invertisment Are you able to log the communication that your server does and check whether the options passed to `textDocument/formatting` are correct? If they are but the server doesn't follow them then it would be a bug. Otherwise I'd be inclined to resolve as invalid.

**Comment by rchl** [comment]
This server does follow the parameters specified in the formatting request (see [the code](https://github.com/theia-ide/typescript-language-server/blob/ab7f35b810d37eda33af35819b0145e286c688b4/server/src/lsp-server.ts#L571-L613)) and reading `.editorconfig` is out of scope so I'm resolving this.

**Comment by lebensterben** [comment]
Thanks for the explanation.

I will reopen the original issue filed in Spacemacs.
