### ISSUE TITLE
eslint/tslint support

### ISSUE THREAD

**Issue by masad-frost** [theia-ide/typescript-language-server#58]
There's currently no linting on the LS. Would be happy to send a PR for this, let m know.

**Comment by svenefftinge** [comment]
It supports tsserver plugins. that si you can add plugins to your tsconfig and they will be used.
We do that in theia for instance: 
https://github.com/theia-ide/theia/blob/master/tsconfig.json#L104

It is faster but unfortunately requires additional configuration.

**Comment by akosyakov** [comment]
I've learned that tsserver can be configured with additional plugins. As an idea, we could add tslint plugin as a dependency to make sure that it installs always instead of requiring projects to install it. It will help to overcome issues like https://github.com/theia-ide/theia/issues/892#issuecomment-417653651. The question will be then how to find tslint config file, we could rely on configuration capacities of LSP and let a client provide it.

**Comment by angelozerr** [comment]
Guys, it seems that you are speaking about my project https://github.com/angelozerr/tslint-language-service 

I had a private conversation with Microsoft guys @egamma and @mjbvz who have contributed to the project and they plan to create a new project for that. When this project will be available, I will give up https://github.com/angelozerr/tslint-language-service
